version: "3"
services:
  db:
    restart: always
    image: postgres:12
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - .env.db

  web:
    build:
      context: .
      dockerfile: Dockerfile
#    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  pgdata: