---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/authentication/login":
    post:
      summary: Get Token
      tags:
      - Auth
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
  "/api/notes":
    get:
      summary: list notes
      security:
      - bearerAuth: []
      responses:
        '200':
          description: successful
    post:
      summary: create note
      security:
      - bearerAuth: []
      responses:
        '200':
          description: successful
  "/api/notes/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show note
      responses:
        '200':
          description: successful
    patch:
      summary: update note
      responses:
        '200':
          description: successful
    put:
      summary: update note
      responses:
        '200':
          description: successful
    delete:
      summary: delete note
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
